# Generated by Django 5.1.1 on 2024-10-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_final',
            new_name='fecha_prestamo_final',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_inicio',
            new_name='fecha_prestamo_inicio',
        ),
    ]
