# Generated by Django 5.1.1 on 2024-10-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_rename_libros_prestamo_libros_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='id_libros',
            new_name='libros_compra',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='id_usuario',
            new_name='usuario_compra',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='libros_compra',
            new_name='libros_prestamo',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='usuario_compra',
            new_name='usuario_prestamo',
        ),
    ]
