# Generated by Django 5.1.1 on 2024-10-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_id_libros_compras_libros_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='libro_precio',
            new_name='libro_precio_total',
        ),
    ]
