# Generated by Django 5.1.1 on 2024-10-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_compras_table_alter_prestamo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compras',
            table='libro_compras',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='libro_prestamos',
        ),
    ]
