# Generated by Django 5.1.1 on 2024-10-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0006_libros_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_valoracion', models.IntegerField(default=0)),
                ('libro_destacado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_destados', to='libros.libros')),
            ],
        ),
    ]
