# Generated by Django 5.1.1 on 2024-10-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destacados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destacos',
            table='libro_destacados',
        ),
    ]
