# Generated by Django 5.1.1 on 2024-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destacados', '0002_alter_destacos_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destacos',
            old_name='calificacion_valoracion',
            new_name='libro_calificacion',
        ),
        migrations.AddField(
            model_name='destacos',
            name='libro_fecha_calificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
