# Generated by Django 5.1.1 on 2024-10-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destacados', '0003_rename_calificacion_valoracion_destacos_libro_calificacion_and_more'),
        ('libros', '0007_alter_libros_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destacos',
            new_name='Destacados',
        ),
    ]
