# Generated by Django 5.1.1 on 2024-10-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destacados', '0004_rename_destacos_destacados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destacados',
            name='libro_fecha_calificacion',
        ),
    ]
