# Generated by Django 5.1.1 on 2024-10-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0006_libros_precio'),
        ('usuarios', '0002_alter_registro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.FloatField(default=0.0)),
                ('fecha_compra', models.DateField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador_carrito', to='usuarios.registro')),
                ('libro', models.ManyToManyField(related_name='libro_carrito', to='libros.libros')),
            ],
            options={
                'db_table': 'carrito_carritocompra',
            },
        ),
    ]
