# Generated by Django 5.1.1 on 2024-10-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0006_libros_precio'),
        ('usuarios', '0002_alter_registro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_comentario', models.DateTimeField(auto_now=True)),
                ('texto_comentario', models.CharField(max_length=200)),
                ('libro_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_libro', to='libros.libros')),
                ('usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_usuario', to='usuarios.registro')),
            ],
        ),
    ]
