# Generated by Django 5.1.1 on 2024-10-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentarios_estrellas_comentario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentarios',
            table='libros_comentarios',
        ),
    ]
