# Generated by Django 5.1.1 on 2024-09-26 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('castegoria', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=30)),
                ('usuarioLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.registro')),
            ],
        ),
    ]
