# Generated by Django 5.1.1 on 2024-10-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='castegoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='libros',
            name='usuarioLibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to='usuarios.registro'),
        ),
    ]
