# Generated by Django 5.1.1 on 2024-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_rename_castegoria_libros_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='titulo',
            field=models.TextField(),
        ),
    ]
