# Generated by Django 5.1.1 on 2024-10-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libros_titulo'),
        ('usuarios', '0002_alter_registro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='usuarioLibro',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to='usuarios.registro'),
        ),
    ]
