# Generated by Django 5.1.1 on 2024-10-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_alter_libros_usuariolibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
