# Generated by Django 5.1.1 on 2024-10-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_libros_precio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libros',
            table='libro_libros',
        ),
    ]
